export const USER_SUCCESS ="USER_SUCCESS";
export const USER_FAIL ="USER_FAIL";
export const USER_SKILLS_SUCCESS ="USER_SKILL_SUCCESS";
export const USER_SKILLS_FAIL ="USER_SKILL_FAIL";
export const USER_TEAM_SKILLS_SUCCESS ="USER_TEAM_SKILL_SUCCESS";
export const USER_TEAM_SKILLS_FAIL ="USER_TEAM_SKILL_FAIL";